### ISSUE TITLE
Failed to load external module babel/register

### ISSUE THREAD

**Issue by MitjaR** [andrejborstnik/track-collector#1]
Jaz sem imel neke probleme z aplikacijo,
sem naredil nov clone iz git. 
Sedaj ob zagonu op-start dobim naslednjo napako:

Failed to load external module babel-core/register
Failed to load external module babel/register

Ali activate.sh ne naloži teh modulov in jih je treba ročno?

########################################
Prej je program javil še:
Local gulp not found in .../track-collector/frontend
Try running: npm install gulp

Pa sem inštalirav gulp in tega ne javi več.

**Comment by andrejborstnik** [comment]
Meni clean pull dela. Ni bilo knjižnice moment (sem nekaj testiral). Mogoče ti zato ni delalo? Gulp se inštalira sam, če ne pride do errorja.
Lahko, da ti ga ni inštaliralo in potem ni nikoli več probalo, ker nisi zbrisal .md5 hasha, s katerim preverjamo ali je sprememba v package.json.
