### ISSUE TITLE
Problem z config -> ReferenceError: config is not defined

### ISSUE THREAD

**Issue by MitjaR** [andrejborstnik/track-collector#2]
Sedaj je napaka z config. 

Terminal ne javi nobene napake. Stran se nalozi, vendar je prazna. 
Ko odprem
GPS (http://localhost:3002/) -> Inspect Element -> Console -> Logging

mi program javi naslednjo napako: 

[vue-router] uncaught error during route navigation: 
ReferenceError: config is not defined
Stack trace:
readSessionCookie@http://localhost:3002/static/js/static/js/frontend.min.js:665:9
["/home/mitja/Documents/GoOpti/track-collector/frontend/src/common/vue-router.js"]</<@http://localhost:3002/static/js/static/js/frontend.min.js:684:18
iterator@http://localhost:3002/static/js/vendor.min.js:107889:7
step@http://localhost:3002/static/js/vendor.min.js:107772:9
runQueue@http://localhost:3002/static/js/vendor.min.js:107780:3
confirmTransition@http://localhost:3002/static/js/vendor.min.js:107918:3
transitionTo@http://localhost:3002/static/js/vendor.min.js:107820:3
init@http://localhost:3002/static/js/vendor.min.js:108489:5
beforeCreate@http://localhost:3002/static/js/vendor.min.js:106649:9
callHook@http://localhost:3002/static/js/vendor.min.js:111175:9
initMixin/Vue.prototype._init@http://localhost:3002/static/js/vendor.min.js:112615:5
Vue$3@http://localhost:3002/static/js/vendor.min.js:112714:3
["/home/mitja/Documents/GoOpti/track-collector/frontend/src/common/vue-router.js"]<@http://localhost:3002/static/js/static/js/frontend.min.js:696:1
s@http://localhost:3002/static/js/static/js/frontend.min.js:1:246
s/<@http://localhost:3002/static/js/static/js/frontend.min.js:1:305
["/home/mitja/Documents/GoOpti/track-collector/frontend/frontend.js"]<@http://localhost:3002/static/js/static/js/frontend.min.js:11:1
s@http://localhost:3002/static/js/static/js/frontend.min.js:1:246
e@http://localhost:3002/static/js/static/js/frontend.min.js:1:425
@http://localhost:3002/static/js/static/js/frontend.min.js:1:11
Loaded-script: static/js/static/js/frontend.min.js  loader.js:16:9
All scripts have been loaded ...  loader.js:44:31
"You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html"

Mogoce ves kje je problem? 

########################################
Moje ugibanje je bilo, da je treba zagnati activate_config.sh, 
ali preimenovati config_default.js, sem malo proskusal pa 
ne znam odpraviti napake.

**Comment by mihic** [comment]
+1

**Comment by andrejborstnik** [comment]
"Config is not defined" v 99.99% primerov pomeni, da je uporabljena spremenjlivka config, brez da bi bila definirana/uvožena (npr. import * as config from 'config').

**Comment by MitjaR** [comment]
Kako se lahko najde lokacijo napake. Sploh ne vem v kateri datoteki je problem.

**Comment by andrejborstnik** [comment]
Meni vse dela, tako da ne vem. Tam kjer je error v konzoli mora biti stack trace errorja in se da najti vrstico, kjer manjka.

**Comment by mihic** [comment]
To se zgodi po clean pull-u. Error kaze nekam v minified JS, tako da ne znava ugotovit od kje je to prislo...

**Comment by andrejborstnik** [comment]
Meni se ob clean pulu to ne zgodi. Tudi na serverju dela (ubuntu 12).
Najprej naredita, da konzola prikazuje lepo formatiran minified js. Potem najdita kje se error zgodi v frontend.min.js (ne v vendor, tam kvečjemu javi error, ga ne sproducira) in odprita na error vrstici. Potem poglejta malo gor/dol in bosta videla v katerem filu sta.

**Comment by andrejborstnik** [comment]
Probajta zdaj. V vue-router.js v readSessionCookie (kot pravi trace) je uporabljen konfig, ce se nisi zlogiran in se moras avtenticirat. Takrat se usuje, ker ni bil definiran. Jaz nisem nikoli videl, ker sem ze zlogiran bil.

**Comment by mihic** [comment]
Dela. Hvala.
