### ISSUE TITLE
Prijava v sistem ni mogoča

### ISSUE THREAD

**Issue by MitjaR** [andrejborstnik/track-collector#5]
Izbira za Auth provider je prazna (na chrome: No data available), tu so opozorila, 
ki jih pri tem javlja program op-start:

Rewriting GET / to /index.html
Rewriting GET /static/js/loader.js to /js/loader.js
Rewriting GET /static/vendor/jquery/dist/jquery.min.js to /vendor/jquery/dist/jquery.min.js
Rewriting GET /static/js/vendor.min.js to /js/vendor.min.js
Rewriting GET /static/js/static/js/frontend.min.js to /js/frontend.min.js
Rewriting GET /static/vendor/vuetify/dist/vuetify.min.css to /vendor/vuetify/dist/vuetify.min.css
(node:11904) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): StatusCodeError: 404 - ""
(node:11904) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Rewriting GET /signin to /index.html
Rewriting GET /static/js/loader.js to /js/loader.js
Rewriting GET /static/vendor/jquery/dist/jquery.min.js to /vendor/jquery/dist/jquery.min.js
Rewriting GET /static/js/vendor.min.js to /js/vendor.min.js
Rewriting GET /static/js/static/js/frontend.min.js to /js/frontend.min.js
Rewriting GET /static/vendor/vuetify/dist/vuetify.min.css to /vendor/vuetify/dist/vuetify.min.css
Not rewriting GET /favicon.ico because the path includes a dot (.) character.
(node:11904) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): StatusCodeError: 404 - ""
(node:11904) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): StatusCodeError: 404 - undefined

**Comment by andrejborstnik** [comment]
Bodi bolj specifičen, iz tega nič ne vidim. Meni vse dela in na serverju tudi.

**Comment by MitjaR** [comment]
Stran singin ne prikaže nobene možnosti za izbiro Auth provider, 
tako da se ni mogoče loginati v aplikacijo.

**Comment by andrejborstnik** [comment]
Si pognal s activate dev, ali activate dev prod?

**Comment by MitjaR** [comment]
./activate.sh dev

**Comment by MitjaR** [comment]
A je treba s prod?

**Comment by andrejborstnik** [comment]
Ne, če poženeš kot prod dobiš denied request, ker proba iti na server. Poglej zakaj request faila.

**Comment by MitjaR** [comment]
Rewriting GET /static/vendor/vuetify/dist/vuetify.min.css to /vendor/vuetify/dist/vuetify.min.css
(node:13623) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): StatusCodeError: 404 - ""
(node:13623) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by andrejborstnik** [comment]
Ja, to mi nič ne pove. Odpri kodo, kjer imaš error in si kaj izpiši. Potem identificiraj kje je napaka in odpravi.

**Comment by MitjaR** [comment]
Jaz tudi ne vem a to kaj pomaga:

Failed to load resource: net::ERR_EMPTY_RESPONSE
signin:1 Uncaught (in promise) RequestError

Kako naj pogledam zaradi katerega dela kode se napaka pojavi?

**Comment by MitjaR** [comment]
In tole se piše: :3102/api/authentication/providers/list Failed to load resource:

**Comment by MitjaR** [comment]
Bom probal se malo sam rešit.

**Comment by andrejborstnik** [comment]
Poglej mail.
